### Holiday calendar crawling


POST {{host}}/calendar/holiday/crawling
content-type: application/json

{
  "year": {{year}},
  "country": "KR"
}

> {%
 client.log(response.body.toString())
 client.global.set("id", response.body.content.id)
 %}

### Find Year calendar

GET {{host}}/calendar/holiday/country/KR/year/{{year}}
content-type: application/json

